[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_hello_world = "H9Le1F13Y9NsnARcX16GQMxHXXfUcxVZUyiBarap6E2a" 

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/elizabethlui/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
